project:
  type: book
  output-dir: docs

number-depth: 2

book:
  title: "Quarto Course Notes"
  subtitle: "Slides and a Book"
  repo-url: https://github.com/DB7-CourseNotes/QuorseNotes
  repo-actions: [issue, source]  
  page-footer:
    left: |
      Copyright Devan Becker, released under Creative Commons Attribution-ShareAlike 4.0.
  sidebar: 
    collapse-level: 2
  page-navigation: true
  chapters:
    - index.qmd
    - part: Setup
      chapters:
        - L01.qmd
    - part: Slides and Book
      chapters:
        - L02-quarto-yml.qmd
        - L03-quarto-book-yml.qmd
        - L04-quarto-slides-yml.qmd
        - L05-advanced.qmd
  appendices:
    - Lab01-R.Rmd
    - Lab02-Python.ipynb
    - DGBecker_QuorseNotes.qmd

format:
  html:
    theme:
      light: [sandstone, smaller_lists.scss]
      dark: [superhero, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    execute:
      echo: true
      code-fold: true
